### ISSUE TITLE
Issues in reproducing the results - Test accuracy drop and inconsistency among different runs

### ISSUE THREAD

**Issue by AndreiBlindu** [FakeEnd/iDNA_ABF#1]
Hi, I'm trying to reproduce the results shown in additional_file.pdf for the H. Sapiens 5hmC dataset. 

I've tried the hyperparameters you specified (batch_size=64, lr=0.0001) leaving the others to the default values in the code and using the DNABERT_3mers model downloaded from huggingface. Below the command: 
`python train.py -model ClassificationDNAbert -batch-size 64 -lr 0.0001 -kmer 3 -path-params ../pretrain/DNAbert_3mer/pytorch_model.bin` 
But I get very poor performance:
[ACC,	SE,		SP,		AUC,	MCC]
0.5128,	1.0000,	0.0000,	0.5000,	0.0000

I tried different DNABERT models (kmer = 3,5,6) with different combinations of hyperparameters:

- learning rate: 0.0001, 0.00005, 0.00001, 0.000005, 0.000001
- dropout: 0.1 (default), 0.0, 0.7 (suggested [here](https://github.com/YUYING07/iDNA-ABF-automl))
- threshold: 0.95 (default), 0.5
- adversarial training: True (default), False
- epochs: up to 200

But eventually the model drops the test accuracy to around 50%

Moreover, I noticed:

- Inconsistent behaviour among runs with the same hyperparameters: sometimes in the first epochs the performance are very good (80%-90%) and others start poorly (around 50%), but eventually always converges to around 50%
- Same behaviour for datasets of different species
- For different runs is different the epoch when the accuracy drops 

Can you please tell me if I'm missing something?
Thanks

**Comment by SilviaBerardelli** [comment]
Similar issue for me. By varying the parameters the accuracy always drops to 50% after a variable number of epochs (2 or even more).

**Comment by FakeEnd** [comment]
Thanks for your feedback. Someone else have reported this issue to me and we have checked this problem. I think you can try two things:

1. Use transformers version of 3.5.0. This verison is two years ago verison, I don't know what they do to the transformers. Once you upgrade to 4.19 or higher something like this issue will happen. You can use this command `pip install transformers==3.5.0` but you may also need to change torch verison. You can try to use torch==1.7/1.8.
2. You can first try to close adversarial training setting [see here](https://github.com/FakeEnd/iDNA_ABF/blob/6feae58080cb8a675590a1fbf3a956baf25142f3/configuration/config_init.py#L25C1-L25C1)  which makes training not stable somtimes, which we think is also casued by transformers package. Becasue we use adverserial attack on transformers embedding which will dependent on implement of  transformers package.

**Comment by AndreiBlindu** [comment]
> Thanks for your feedback. Someone else have reported this issue to me and we have checked this problem. I think you can try two things:
> 
> 1. Use transformers version of 3.5.0. This verison is two years ago verison, I don't know what they do to the transformers. Once you upgrade to 4.19 or higher something like this issue will happen. You can use this command `pip install transformers==3.5.0` but you may also need to change torch verison. You can try to use torch==1.7/1.8.
> 2. You can first try to close adversarial training setting [see here](https://github.com/FakeEnd/iDNA_ABF/blob/6feae58080cb8a675590a1fbf3a956baf25142f3/configuration/config_init.py#L25C1-L25C1)  which makes training not stable somtimes, which we think is also casued by transformers package. Becasue we use adverserial attack on transformers embedding which will dependent on implement of  transformers package.

Thanks for your response. Trying without adversarial training didn't solve my issue, I've tried what you said in the first point (transformers 3.5.0 and torch both 1.7 and 1.8) and I got the following error:
`cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler'`

I downgraded torch to 1.4.0 to solve this issue but now I have another error:
`RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
I'm using cuda 11.8 on my machine, since it's a shared cluster I don't have sudo permissions to change it, but I can change the cuda version in my conda environment.

In order to avoid a version matching nightmare, could you please provide a requirements file with the right versions of all the packages?
Thanks

**Comment by FakeEnd** [comment]
Sorry, my environment is on my previous lab and I have no access to it now. But you can try to install transformers==4.18.0. Most people told me this is enough to make model works. If it still not works, I will ask somebody to generate the requirements for you.

**Comment by AndreiBlindu** [comment]
> Sorry, my environment is on my previous lab and I have no access to it now. But you can try to install transformers==4.18.0. Most people told me this is enough to make model works. If it still not works, I will ask somebody to generate the requirements for you.

Thank you very much, now it worked and I was able to get result close to those shown in the paper in most of the cases. However, in some runs (like 3 out of 10) it still happens that the training goes unstable and drops to about 50% test accuracy (both with and without adversarial). 
Therefore I think it would be helpful for anyone interested in this awesome model to have a requirements file if you can upload it somehow, but for now my issue seems to be pretty much solved.

Thank you again.

**Comment by FakeEnd** [comment]
Thanks for your feedback. I don't know what they do to the transformers 😂. I will check that in future and upload a a requirements file. If you have any other questions, welcome to ask.
